# Tensor Basics

In this tutorial, we will learn to work with tensors. We will learn what tensors are, some basic operations, converting from `numpy` arrays to tensors and back, etc.

In `pytorch`, everything is based on tensor operations. A tensor can have different dimensions. It can be 1D, 2D, 3D, or more.

First, we will import `torch`.

In [1]:
import torch

Then we will make a tensor of size 1, like a scalar value, and print it. 

In [3]:
x = torch.empty(1)
print(x)

tensor([0.])


If we change the size to 3, it will be like a 1D vector with 3 elements.

In [4]:
x = torch.empty(3)
print(x)

tensor([0., 0., 0.])


We can also make the tensor 2D. So, if we wanted to make a 2x3 (2 rows, 3 columns) matrix, it would look like:

In [5]:
x = torch.empty(2, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.6114e-19]])


You can keep adding dimensions onto the tensor to make it 3D, 4D, etc. 

You can create a tensor with random values using the code below. It will make a 2x2 matrix.

In [6]:
x = torch.rand(2, 2)
print(x)

tensor([[0.0601, 0.8997],
        [0.6243, 0.9113]])


You can make a tensor containing only zeros, just like with `numpy`. This is done using the code below:

In [8]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


You can make a tensor containing only ones. This is done using the code below:

In [9]:
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


You can also give a tensor a specific data type. You can check the specific data type of an object using:

In [10]:
x = torch.ones(2,2)
print(x.dtype)

torch.float32


By default, it is a `float32`. However, we can pass the `dtype =` argument when making a tensor to assign it a specific data type:

In [11]:
x = torch.ones(2,2, dtype = torch.int)
print(x.dtype)

torch.int32


You can also use `dtype = torch.double`, `torch.float16`, and others. 

You can check the size of a tensor by using the function `size()`:

In [12]:
x = torch.ones(2,2, dtype = torch.int)
print(x.size())

torch.Size([2, 2])


You can construct a tensor from data, such as a `Python` list. This is done by putting the list inside of `torch.tensor()`.

In [13]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


Now we will discuss some basic operations we can do between tensors. First, we will make 2 2D tensors with random values.

In [14]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.2747, 0.8900],
        [0.8235, 0.6036]])
tensor([[0.7550, 0.9691],
        [0.2407, 0.9201]])


You can do many operations between tensors. The first is addition, which will do element-wise addition. It adds up each of the entries. This can be done manually or with `torch.add()`.

In [17]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x + y
print(z)

w = torch.add(x,y)
print(w)

tensor([[1.2900, 0.6404],
        [1.1299, 1.1490]])
tensor([[1.2900, 0.6404],
        [1.1299, 1.1490]])


You can also do an in-place addition. You can add all of the elements of `x` into `y`, modifying the `y` in the process.

In [18]:
x = torch.rand(2,2)
y = torch.rand(2,2)

y.add_(x)
print(y)

tensor([[0.9138, 1.3466],
        [1.1997, 0.7422]])


As a note, in `pytorch`, every function that has a trailing underscore, such as `.add_`, will do an in place operation. It will modify the variable that it is applied on. 

You can also do subtraction, which will do element-wise subtraction. It subtracts each of the entries. This can be done manually or with `torch.sub()`.

In [19]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x - y
print(z)

w = torch.sub(x,y)
print(w)

tensor([[-0.5924, -0.3539],
        [-0.1132,  0.0298]])
tensor([[-0.5924, -0.3539],
        [-0.1132,  0.0298]])


You can also do multiplication, which will do element-wise multiplication. It will multiply each of the entries. This can be done manually or with `torch.mul()`.

In [20]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x * y
print(z)

w = torch.mul(x,y)
print(w)

tensor([[0.0463, 0.3065],
        [0.4455, 0.0703]])
tensor([[0.0463, 0.3065],
        [0.4455, 0.0703]])


And, if we wanted to do an in-place multiplication, it would look like:

In [22]:
x = torch.rand(2,2)
y = torch.rand(2,2)

y.mul_(x)
print(y)

tensor([[0.1285, 0.1492],
        [0.1943, 0.2578]])


You can also do devision, which will do element-wise division. It will divide each of the entries. This can be done manually or with `torch.div()`.

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x / y
print(z)

w = torch.div(x,y)
print(w)

And you can, of course, do in-place division:

In [24]:
x = torch.rand(2,2)
y = torch.rand(2,2)

y.div_(x)
print(y)

tensor([[1.1077, 0.3678],
        [1.0812, 1.4758]])


In addition to doing basic operations with tensors, we can also do tensor slicing operations. So, let's say we have a tensor of size 5x3:

In [25]:
x = torch.rand(5,3)
print(x)

tensor([[0.3222, 0.0047, 0.8137],
        [0.1282, 0.7502, 0.2362],
        [0.2459, 0.2942, 0.9547],
        [0.6297, 0.1408, 0.8585],
        [0.3333, 0.1490, 0.1283]])


So, if we want to get all the rows but only one column with the code below. The colon in the brackets `[:, ]` means we are selecting all the rows. If we also wanted all the columns, the colon would move to the other side: `[, :]`. 

In [27]:
x = torch.rand(5,3)
print(x)
print(x[:, 0])

tensor([[0.0208, 0.2400, 0.3460],
        [0.3208, 0.8719, 0.7479],
        [0.1332, 0.3393, 0.1753],
        [0.7737, 0.7082, 0.0862],
        [0.6120, 0.2471, 0.2916]])
tensor([0.0208, 0.3208, 0.1332, 0.7737, 0.6120])


To select row number one and all columns, you would do: (as a note, this will print the second row, since indexing in Python starts 0)

In [29]:
x = torch.rand(5,3)
print(x)
print(x[1, :])

tensor([[0.7469, 0.7364, 0.2348],
        [0.9669, 0.0319, 0.6656],
        [0.1240, 0.2883, 0.2759],
        [0.3018, 0.0395, 0.8819],
        [0.6598, 0.5116, 0.1011]])
tensor([0.9669, 0.0319, 0.6656])


To print a single element at position 1, 1:

In [30]:
x = torch.rand(5,3)
print(x)
print(x[1, 1])

tensor([[0.7434, 0.7496, 0.2833],
        [0.2401, 0.8853, 0.8996],
        [0.1145, 0.2007, 0.6705],
        [0.7648, 0.5765, 0.2334],
        [0.7602, 0.3160, 0.2194]])
tensor(0.8853)


As we see above, the slicing prints a tensor rather than the single value. To print the actual value and not a tensor, you can do:

In [31]:
x = torch.rand(5,3)
print(x)
print(x[1, 1].item())

tensor([[0.1424, 0.1685, 0.6989],
        [0.0344, 0.5201, 0.3753],
        [0.7418, 0.6525, 0.3286],
        [0.7700, 0.3047, 0.7777],
        [0.1306, 0.3025, 0.3821]])
0.5200650095939636


As a note, you can only use this method if you have one element in the tensor. 

Now, we will talk about reshaping a tensor. So, let's say we have a tensor with size 4x4:

In [32]:
x = torch.rand(4,4)
print(x)

tensor([[0.6477, 0.3123, 0.8341, 0.1238],
        [0.6051, 0.5037, 0.1787, 0.5225],
        [0.9020, 0.5154, 0.3734, 0.4030],
        [0.0902, 0.9430, 0.8340, 0.6917]])


If you want to reshape it, you can call the `.view()` method. In this example, it will turn the 4x4 tensor into a 1D vector.

In [33]:
x = torch.rand(4,4)
print(x)

y = x.view(16)
print(y)

tensor([[0.1952, 0.2690, 0.2322, 0.4032],
        [0.9568, 0.2345, 0.3647, 0.2700],
        [0.0770, 0.9685, 0.6735, 0.6144],
        [0.7067, 0.7158, 0.7546, 0.4169]])
tensor([0.1952, 0.2690, 0.2322, 0.4032, 0.9568, 0.2345, 0.3647, 0.2700, 0.0770,
        0.9685, 0.6735, 0.6144, 0.7067, 0.7158, 0.7546, 0.4169])


The number of elements must still be the same when reshaping a tensor. So, in the example above, we have a 4x4 tensor, which is 16 elements, thus when we reshape, we should have 16.

However, if we want to remove a value in 1 dimension, we can simply say -1 and specify the other dimension. `pytorch` will automatically determine the right size for it.

In [36]:
x = torch.rand(4,4)
print(x)

y = x.view(-1, 8)
print(y)

print(y.size())

tensor([[0.1375, 0.8445, 0.9895, 0.5082],
        [0.5784, 0.7246, 0.2125, 0.2004],
        [0.0809, 0.4977, 0.6042, 0.2517],
        [0.7268, 0.1380, 0.0173, 0.4146]])
tensor([[0.1375, 0.8445, 0.9895, 0.5082, 0.5784, 0.7246, 0.2125, 0.2004],
        [0.0809, 0.4977, 0.6042, 0.2517, 0.7268, 0.1380, 0.0173, 0.4146]])
torch.Size([2, 8])


And, as another example:

In [39]:
x = torch.rand(4,4)
print(x)

y = x.view(-1, 2)
print(y)

print(y.size())

tensor([[0.1670, 0.6221, 0.4145, 0.1484],
        [0.4753, 0.4731, 0.5683, 0.7236],
        [0.6730, 0.6247, 0.4929, 0.0475],
        [0.7871, 0.4624, 0.5697, 0.3129]])
tensor([[0.1670, 0.6221],
        [0.4145, 0.1484],
        [0.4753, 0.4731],
        [0.5683, 0.7236],
        [0.6730, 0.6247],
        [0.4929, 0.0475],
        [0.7871, 0.4624],
        [0.5697, 0.3129]])
torch.Size([8, 2])


Now, we will talk about converting between a `numpy` array and tensors.

First, lets import `numpy`.

In [40]:
import numpy as np

Now, let's convert between a `numpy` array and tensor. First, from tensor to `numpy` array.

In [43]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


Now, we have to be careful because, if the tensor is on the CPU rather than the GPU, then both objects will sahre the same memory location. This means that, if we change one, then we will also change the other.  

So, for example, if we modify `a` or `b` in-place, they will both change:

In [45]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


If you have a `numpy` array and want to convert it into a tensor, you do: (this will, by default, specify the data type float64) 

In [50]:
a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


Now again we have to be careful if we modify one. If we modify the `numpy` array by incrementing each element by 1, it will also change the tensor. Remember this only happens when your tensor is on the CPU rather than the GPU.

In [51]:
a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


You can check if CUDA is available by typing:

In [55]:
torch.cuda.is_available()

False

If you have CUDA available, you can specify the CUDA device by:

`torch.cuda.is_available()
    device = torch.device("cuda")`

Then, we if want to create a tensor on the GPU, we can:

`x = torch.ones(5, device = device)` 

You can also first create the tensor and then put it on the GPU:

`y = torch.ones(5)
    y = y.to(device)`

Now, if you do an operation, it will be done on the GPU. However, you have to be careful because you cannot convert a GPU tensor back to `numpy`. `numpy` can only work with CPU tensors. 

So, we would have to move the tensor back to the CPU. This can be done by:

`y = y.to("cpu")`

As one last thing, a lot of times when a tensor is created, you will see the argument `requires_grad = True`. By default, it is `False`. By specifiying the argument to `True`, it will tell `pytorch` that it will need to calculate the gradients for this tensor later in your optimization steps.

In [56]:
x = torch.ones(5, requires_grad = True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


Whenever you have a variable in your model that you want to optimize, then you need the gradients, so you need to specify this argument. We will talk about this more in the next tutorial. 